# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"3\n\x0e\x43ommandRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"\x1f\n\x0c\x43ommandReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"l\n\x0b\x43hatMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0e\n\x06sender\x18\x03 \x01(\t\x12\x10\n\x08receiver\x18\x04 \x01(\t\x12\r\n\x05group\x18\x05 \x01(\t\x12\x0b\n\x03msg\x18\x06 \x01(\t\"\"\n\x0e\x43onnectRequest\x12\x10\n\x08username\x18\x01 \x01(\t2\x83\x01\n\x0b\x43hatService\x12\x37\n\x0bSendCommand\x12\x14.chat.CommandRequest\x1a\x12.chat.CommandReply\x12;\n\x0eStreamMessages\x12\x14.chat.ConnectRequest\x1a\x11.chat.ChatMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDREQUEST']._serialized_start=20
  _globals['_COMMANDREQUEST']._serialized_end=71
  _globals['_COMMANDREPLY']._serialized_start=73
  _globals['_COMMANDREPLY']._serialized_end=104
  _globals['_CHATMESSAGE']._serialized_start=106
  _globals['_CHATMESSAGE']._serialized_end=214
  _globals['_CONNECTREQUEST']._serialized_start=216
  _globals['_CONNECTREQUEST']._serialized_end=250
  _globals['_CHATSERVICE']._serialized_start=253
  _globals['_CHATSERVICE']._serialized_end=384
# @@protoc_insertion_point(module_scope)
